-- =============================================
-- Migration: V1__init_schema.sql
-- Description: Initial database schema setup
-- Database: Oracle 21.3.0.0
-- Created: Auto-generated by Flyway setup
-- =============================================

-- Example: Create a sample configuration table
CREATE TABLE app_config (
    config_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    config_key VARCHAR2(255) NOT NULL,
    config_value VARCHAR2(4000),
    description VARCHAR2(1000),
    is_active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_app_config_key UNIQUE (config_key)
);

-- Create index for faster lookups
CREATE INDEX idx_app_config_key ON app_config(config_key);

-- Add comments
COMMENT ON TABLE app_config IS 'Application configuration table';
COMMENT ON COLUMN app_config.config_id IS 'Primary key';
COMMENT ON COLUMN app_config.config_key IS 'Configuration key name';
COMMENT ON COLUMN app_config.config_value IS 'Configuration value';
COMMENT ON COLUMN app_config.description IS 'Description of the configuration';
COMMENT ON COLUMN app_config.is_active IS 'Active flag (1=active, 0=inactive)';
COMMENT ON COLUMN app_config.created_at IS 'Record creation timestamp';
COMMENT ON COLUMN app_config.updated_at IS 'Record last update timestamp';

-- Insert sample data
INSERT INTO app_config (config_key, config_value, description) 
VALUES ('app.version', '1.0.0', 'Application version');

INSERT INTO app_config (config_key, config_value, description) 
VALUES ('app.environment', 'development', 'Current environment');

COMMIT;
