-- =============================================================================
-- 01 - SCHEMA STRUCTURE FINAL
-- RUN FIRST
-- Table/column/constraint/schema migrations only.
-- NOTE: the two idempotent VARCHAR2->CLOB schema migration blocks contain an
-- internal UPDATE only to copy error_message into the temporary CLOB column.
-- No business/config MERGE/INSERT/UPDATE is included here.
-- No index DDL. No GATHER_TABLE_STATS.
-- =============================================================================



-- EXCLUDED FOR PRODUCTION DEPLOYMENT: table statistics collection intentionally skipped

-- EXCLUDED FOR PRODUCTION DEPLOYMENT: table statistics collection intentionally skipped



BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyMultLinearRegrResultPen"
ADD (
    "coefficient_variable_name_1"  VARCHAR2(255),
    "coefficient_variable_1"       NUMBER,
    "coefficient_variable_name_2"  VARCHAR2(255),
    "coefficient_variable_2"       NUMBER,
    "coefficient_variable_name_3"  VARCHAR2(255),
    "coefficient_variable_3"       NUMBER,
    "kolmogorov_smirnov"           NUMBER,
    "lagrange_multiplier"          NUMBER,
    "variance_inflation_factor"    NUMBER,
    "anderson_darling"             NUMBER,
    "breusch_pagan"                NUMBER,
    "durbin_watson"                NUMBER,
    "shapiro_wilk"                 NUMBER
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyFlImpact"
ADD (
    "coefficient_variable_name_1" VARCHAR2(255),
    "coefficient_variable_1"      NUMBER,
    "coefficient_variable_name_2" VARCHAR2(255),
    "coefficient_variable_2"      NUMBER,
    "coefficient_variable_name_3" VARCHAR2(255),
    "coefficient_variable_3"      NUMBER,
    "kolmogorov_smirnov"          NUMBER,
    "lagrange_multiplier"         NUMBER,
    "variance_inflation_factor"   NUMBER,
    "anderson_darling"            NUMBER,
    "breusch_pagan"               NUMBER,
    "durbin_watson"               NUMBER,
    "shapiro_wilk"                NUMBER,
	"r_squared"          		  NUMBER,
    "p_value"                     NUMBER DEFAULT 0,
    "f_statistic"                 NUMBER DEFAULT 0,
    "df_regr"                     NUMBER(19,0),
    "df_resd"                     NUMBER(19,0),
    "df_total"                    NUMBER(19,0),
    "ols_pass_count"              NUMBER(1,0) DEFAULT 0 NOT NULL,
    "aic"                         NUMBER DEFAULT 0,
    "bic"                         NUMBER DEFAULT 0,
    "sic"                         NUMBER DEFAULT 0,
    "mult_r_squared"              NUMBER DEFAULT 0
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


-----------------------------

BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyMultLinearRegrResultPen"
ADD (
    "intercept_name"       VARCHAR2(255),
    "intercept"            NUMBER,
    "p_value_variable_1"   NUMBER,
    "p_value_variable_2"   NUMBER,
    "p_value_variable_3"   NUMBER,
    "p_value_intercept"    NUMBER
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyFlImpact"
ADD (
    "intercept_name"       VARCHAR2(255),
    "intercept"            NUMBER,
    "p_value_variable_1"   NUMBER,
    "p_value_variable_2"   NUMBER,
    "p_value_variable_3"   NUMBER,
    "p_value_intercept"    NUMBER
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


-- EXCLUDED FOR PRODUCTION DEPLOYMENT: table statistics collection intentionally skipped

BEGIN
    EXECUTE IMMEDIATE q'~CREATE TABLE NTT_RISK_MODELLING."TableElementAliases"
(
    "pkid"          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "mapping_tabel" VARCHAR2(255 CHAR) NOT NULL,
    "type_element"  VARCHAR2(255 CHAR) NOT NULL,
    "table_alias"   VARCHAR2(255 CHAR) NOT NULL,
    "is_active"     NUMBER(1) DEFAULT 1 NOT NULL,
    "created_by"    VARCHAR2(50 CHAR),
    "created_date"  DATE DEFAULT SYSDATE NOT NULL,
    "created_host"  VARCHAR2(50 CHAR) DEFAULT 'localhost' NOT NULL,
    "updated_by"    VARCHAR2(50 CHAR),
    "updated_date"  DATE,
    "updated_host"  VARCHAR2(50 CHAR),
    "is_deleted"    NUMBER(1) DEFAULT 0 NOT NULL,
    "deleted_by"    VARCHAR2(50 CHAR),
    "deleted_date"  DATE,
    "deleted_host"  VARCHAR2(50 CHAR),
    CONSTRAINT "PK_TableElementAliases" PRIMARY KEY ("pkid"),
    CONSTRAINT "UQ_TableElementAliases" UNIQUE ("mapping_tabel", "type_element"),
    CONSTRAINT "CK_TEA_IsActive" CHECK ("is_active" IN (0, 1)),
    CONSTRAINT "CK_TEA_IsDeleted" CHECK ("is_deleted" IN (0, 1))
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/



BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyOdrForecast"
ADD "is_selected" NUMBER(1,0) DEFAULT 0 NOT NULL~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyOdrForecast"
ADD "transform_odr_type" VARCHAR2(20) NULL~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyOdrForecast"
ADD "best_model" NUMBER(1,0) DEFAULT 0 NOT NULL~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


-- Idempotent VARCHAR2 -> CLOB migration.
-- If error_message is already CLOB, this block does nothing.
DECLARE
    v_data_type VARCHAR2(128);
BEGIN
    SELECT MAX(data_type)
      INTO v_data_type
      FROM ALL_TAB_COLUMNS
     WHERE owner = 'NTT_WORKFLOW'
       AND table_name = 'WorkflowRunDetail'
       AND column_name = 'error_message';

    IF v_data_type IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'NTT_WORKFLOW.WorkflowRunDetail.error_message not found');
    ELSIF v_data_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NTT_WORKFLOW."WorkflowRunDetail" ADD ("error_message_clob" CLOB)';
        EXECUTE IMMEDIATE 'UPDATE NTT_WORKFLOW."WorkflowRunDetail" SET "error_message_clob" = TO_CLOB("error_message")';
        COMMIT;
        EXECUTE IMMEDIATE 'ALTER TABLE NTT_WORKFLOW."WorkflowRunDetail" DROP COLUMN "error_message"';
        EXECUTE IMMEDIATE 'ALTER TABLE NTT_WORKFLOW."WorkflowRunDetail" RENAME COLUMN "error_message_clob" TO "error_message"';
    END IF;
END;
/


------------

-- Idempotent VARCHAR2 -> CLOB migration.
-- If error_message is already CLOB, this block does nothing.
DECLARE
    v_data_type VARCHAR2(128);
BEGIN
    SELECT MAX(data_type)
      INTO v_data_type
      FROM ALL_TAB_COLUMNS
     WHERE owner = 'NTT_WORKFLOW'
       AND table_name = 'WorkflowSimulationDetail'
       AND column_name = 'error_message';

    IF v_data_type IS NULL THEN
        RAISE_APPLICATION_ERROR(-20002, 'NTT_WORKFLOW.WorkflowSimulationDetail.error_message not found');
    ELSIF v_data_type <> 'CLOB' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NTT_WORKFLOW."WorkflowSimulationDetail" ADD ("error_message_clob" CLOB)';
        EXECUTE IMMEDIATE 'UPDATE NTT_WORKFLOW."WorkflowSimulationDetail" SET "error_message_clob" = TO_CLOB("error_message")';
        COMMIT;
        EXECUTE IMMEDIATE 'ALTER TABLE NTT_WORKFLOW."WorkflowSimulationDetail" DROP COLUMN "error_message"';
        EXECUTE IMMEDIATE 'ALTER TABLE NTT_WORKFLOW."WorkflowSimulationDetail" RENAME COLUMN "error_message_clob" TO "error_message"';
    END IF;
END;
/



BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_WORKFLOW."WorkflowDetailDraft"
ADD "source_type" VARCHAR2(20) DEFAULT 'MANUAL' NOT NULL~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_WORKFLOW."WorkflowDetailDraft"
MODIFY (
    "source_type"
    CONSTRAINT WDD_SOURCE_TYPE_CK
    CHECK ("source_type" IN ('MANUAL', 'TEMPLATE', 'DEPENDENCY'))
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


DECLARE
    v_column_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_column_count
      FROM ALL_TAB_COLUMNS
     WHERE OWNER = 'NTT_RISK_MODELLING'
       AND TABLE_NAME = 'WorkflowPdSegment'
       AND COLUMN_NAME = 'model_seq';

    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE NTT_RISK_MODELLING."WorkflowPdSegment"
            ADD ("model_seq" NUMBER(19) NULL)';
    END IF;
END;
/


--- mulai baru di dev portal belum naik
BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyMultLinearRegrResultPen" ADD (
    "jarque_bera" NUMBER NULL,
    "breusch_godfrey" NUMBER NULL
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE q'~ALTER TABLE NTT_RISK_MODELLING."PyFlImpact" ADD (
    "jarque_bera" NUMBER NULL,
    "breusch_godfrey" NUMBER NULL
)~';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -2264) THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/
